### ISSUE TITLE
Nested folder notes are visible on the latest version of Obsidian

### ISSUE THREAD

**Issue by reply2za** [LostPaul/obsidian-folder-notes#145]
When restarting Obsidian with folder notes enabled, I can still see the folder note as a separate note under the folder name for nested folder notes. When I say nested, I mean a folder that is a folder note inside another folder that is also a folder note. It seems to not happen for top level folder notes. I tried uninstalling and reinstalling Folder notes and it fixes the issue until I close and re-open Obsidian. 

e.g. (we have 3 nested folders) 
`someFolder/folderWithFolderNoteA/folderWithFolderNoteB`
In this case: `folderWithFolderNoteB` will have a visible sub-note called folderWithFolderNoteB despite the plugin being enabled.

I'm not sure if it's due to the latest version of Obsidian, but I have only noticed this happening recently. 

Folder notes version: 1.7.26
Obsidian version: 1.7.1

**Comment by mwsmedia** [comment]
I'm seeing it in top-level folders with folder notes, too. In addition, the underlined name of folders with folder notes is no longer underlined. These seem connected, for the underline disappeared when the folder notes appeared..!

**Comment by lx0n2acl** [comment]
only workaround im seeing is to go into the plugin options, click on "excluded folders" tab, click on "manage" button for "Exclude folder default settings", and then toggle "include subfolders" - seems to resolve the issue for the session

**Comment by LostPaul** [comment]
Did the new version I published fix this issues?

**Comment by mwsmedia** [comment]
> Does the new version I published fix this issue?

Just updated -- it appears to! Underlines are back on the folders, and the folder note note is no longer visible. Thanks!

**Comment by lx0n2acl** [comment]
Thanks @LostPaul - love the plugin and I rely on it heavily. Awesome work, much appreciated.

**Comment by lx0n2acl** [comment]
@LostPaul - Actually I'm still seeing this behavior on nested folders, specifically after the 5th level

**Comment by mwsmedia** [comment]
Indeed, I spoke too soon. Closing and re-opening the vault, the folder underlines are gone and the folder note note is once again visible for all folders.

**Comment by LostPaul** [comment]
I'll look into this again tomorrow I might've an idea what the cause for this issues is.

**Comment by LostPaul** [comment]
Does this release change anything? https://github.com/LostPaul/obsidian-folder-notes/releases/tag/1.7.30-4-beta
You can use [brat](https://github.com/TfTHacker/obsidian42-brat) to install it.

**Comment by reply2za** [comment]
Although your last update was working great. 

The latest Obsidian update (v1.7.2) re-introduces this issue for me. There are some api related updates that might've broken something. 

Api updates:
- https://docs.obsidian.md/Plugins/Guides/Understanding+deferred+views
- https://github.com/obsidianmd/obsidian-api/blob/master/CHANGELOG.md#v172-insider

**Comment by LostPaul** [comment]
> Your last update was working great, but the latest Obsidian update (v1.7.2) re-introduces this issue for me. There are some api related updates that might've broken something. 
> 
> Api updates:
> - https://docs.obsidian.md/Plugins/Guides/Understanding+deferred+views
> - https://github.com/obsidianmd/obsidian-api/blob/master/CHANGELOG.md#v172-insider

Does that include the beta released I mentioned here?

**Comment by reply2za** [comment]
I take my previous message back. I am certain I had restarted the app before writing my message but only now did it start working. Furthermore, if I restart the app again it continues to work correctly. I have not tried the beta version yet but only issue I have now with the current version is that the open/close folder carrots are misaligned. 

![image](https://github.com/user-attachments/assets/5904e387-a334-47ae-93b2-1b7097a6cadc)

**Comment by LostPaul** [comment]
> I take my previous message back. I am certain I had restarted the app before writing my message but only now did it start working. Furthermore, if I restart the app again it continues to work correctly. I have not tried the beta version yet but only remaining issue I have with the current version is that the open/close folder carrots are misaligned.
> 
> ![image](https://private-user-images.githubusercontent.com/37006843/369130627-5904e387-a334-47ae-93b2-1b7097a6cadc.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NDA3ODMsIm5iZiI6MTcyNjg0MDQ4MywicGF0aCI6Ii8zNzAwNjg0My8zNjkxMzA2MjctNTkwNGUzODctYTMzNC00N2FlLTkzYjItMWI3MDk3YTZjYWRjLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxMzU0NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWIyZDgyMGYwMGJlODNjZGQ1NWE0OGNhNzI3N2QxY2M5MDQ4MGRjOGI0OTA2YTJiOThjNTQ5ZTE1MDhjNWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YR34oxhR8_kEhMMr9ZmLMWNRL5_nXRCs1_q_ayr7BVg)

Try the beta release and see #148 for the style issue it will be fixed tomorrow.

**Comment by reply2za** [comment]
Works great, thanks!

**Comment by reply2za** [comment]
@LostPaul Actually I have noticed that I am seeing the same issue but instead of it being on the second nested folder note it is now on the third nested folder note. Could you please re-open this issue?

**Comment by mwsmedia** [comment]
This is fixed, near as I can tell SO LONG AS you don't have the Make.MD plugin also installed. Note that the issue pops up even if Make.MD's own folder note functionality is turned off.  In other words, Folder Notes and Make.MD are incompatible.

**Comment by reply2za** [comment]
I had noticed it on mobile today. Restarted the app and it went away. Post-restart I can't recreate the issue and am not sure if or when it'll come back. Btw I have only noticed it on mobile (IOS) since the update, but it appears to be a hit or miss. And yes my device is running the latest version of the plugin. If it doesn't come back again in a few days then I'll go ahead and close this issue.

And thanks LostPaul for your dedication and support in keeping this great plugin stable.

**Comment by petergaultney** [comment]
I just started using Folder Notes (1.7.35) - I'm running into this issue on Android, v1.8.7 (191).  

It's not consistent - some folders will display with the underline (and the same-name note is hidden) and others don't.

I'm using Obsidian Sync, in case that seems relevant. The other plugin that might _maybe_ be messing with stuff is Custom File Explorer Sorting. But I use all these same plugins on my laptop, and I can see on my laptop that everything works normally/as expected. So it's apparently just a mobile issue.

What's really weird is that this workaround [described above](https://github.com/LostPaul/obsidian-folder-notes/issues/145#issuecomment-2334588418) seems to actually work - at least, I followed the steps and suddenly it seems as though Folder Notes is basically working?

**Comment by petergaultney** [comment]
I just started using Folder Notes (1.7.35) - I'm running into this issue on Android, v1.8.7 (191).  

It's not consistent - some folders will display with the underline (and the same-name note is hidden) and others don't.

I'm using Obsidian Sync, in case that seems relevant. The other plugin that might _maybe_ be messing with stuff is Custom File Explorer Sorting. But I use all these same plugins on my laptop, and I can see on my laptop that everything works normally/as expected. So it's apparently just a mobile issue.

What's really weird is that this workaround [described above](https://github.com/LostPaul/obsidian-folder-notes/issues/145#issuecomment-2334588418) seems to actually work - at least, I followed the steps and suddenly it seems as though Folder Notes is basically working?
